export { default as HomePage } from './home'
export { default as ContactPage } from './contact'
export { default as CollectionPage } from './collection'
export { default as ProductDetailPage } from './productDetail'
export { default as NotFoundError } from './errorNotFound'
export { default as CheckoutPage } from './checkout'
export { default as StoryPage } from './ourStory'
